- intent: faq/ask_getTemplateApplication
  examples: |
    - Cum fac o cerere?
    - Ai un model de cerere pentru secretariat?
    - Există vreun model de cerere pentru secretariat?
    - Îmi poți arâta un model de cerere?
    - Îmi poți trimite un model de cerere?
    